use std::fmt::Write;

use crate::model::{
    Cell, CellStyle, ColorSpec, ComponentScene, Project, RectSpec, WidgetKind, WidgetSpec,
};

#[must_use]
pub fn export_art(project: &Project) -> String {
    let mut output = String::new();
    writeln!(output, "use ratatui::{{").unwrap();
    writeln!(output, "    buffer::Buffer,").unwrap();
    writeln!(output, "    layout::Rect,").unwrap();
    writeln!(output, "    style::{{Color, Modifier, Style}},").unwrap();
    writeln!(output, "    widgets::Widget,").unwrap();
    writeln!(output, "}};\n").unwrap();
    writeln!(output, "pub struct {}Art;\n", rust_type_name(&project.name)).unwrap();
    writeln!(output, "impl Widget for {}Art {{", rust_type_name(&project.name)).unwrap();
    writeln!(output, "    fn render(self, area: Rect, buf: &mut Buffer) {{").unwrap();
    writeln!(output, "        const WIDTH: u16 = {};", project.canvas().width).unwrap();
    writeln!(output, "        const HEIGHT: u16 = {};", project.canvas().height).unwrap();
    writeln!(output, "        let origin_x = area.x + area.width.saturating_sub(WIDTH) / 2;").unwrap();
    writeln!(output, "        let origin_y = area.y + area.height.saturating_sub(HEIGHT) / 2;").unwrap();

    for y in 0..project.canvas().height {
        for x in 0..project.canvas().width {
            let point = crate::model::Point::new(x, y);
            let Some(cell) = project.canvas().composite_cell(point) else {
                continue;
            };
            if cell.transparent || cell.glyph == " " {
                continue;
            }
            let style = rust_style(&cell.style);
            writeln!(
                output,
                "        if origin_x + {x} < area.right() && origin_y + {y} < area.bottom() {{"
            )
            .unwrap();
            writeln!(
                output,
                "            buf[((origin_x + {x}), (origin_y + {y}))].set_symbol({:?}).set_style({style});",
                cell.glyph
            )
            .unwrap();
            writeln!(output, "        }}").unwrap();
        }
    }

    writeln!(output, "    }}").unwrap();
    writeln!(output, "}}").unwrap();
    output
}

#[must_use]
pub fn export_animation(project: &Project) -> String {
    let mut output = String::new();
    writeln!(output, "// Generated by Ratatelier.").unwrap();
    writeln!(output, "pub const FRAME_DURATIONS_MS: &[u64] = &[").unwrap();
    for frame in &project.frames {
        writeln!(output, "    {},", frame.duration_ms).unwrap();
    }
    writeln!(output, "];\n").unwrap();
    writeln!(output, "pub const FRAMES: &[&[&str]] = &[").unwrap();
    for frame in &project.frames {
        writeln!(output, "    &[").unwrap();
        for y in 0..frame.canvas.height {
            let mut line = String::new();
            for x in 0..frame.canvas.width {
                let glyph = frame
                    .canvas
                    .composite_cell(crate::model::Point::new(x, y))
                    .map_or(" ", |cell| cell.glyph.as_str());
                line.push_str(glyph);
            }
            writeln!(output, "        {:?},", line).unwrap();
        }
        writeln!(output, "    ],").unwrap();
    }
    writeln!(output, "];").unwrap();
    output
}

#[must_use]
pub fn export_component(project: &Project) -> String {
    let mut output = String::new();
    let type_name = format!("{}Component", rust_type_name(&project.name));
    writeln!(output, "use ratatui::{{").unwrap();
    writeln!(output, "    buffer::Buffer,").unwrap();
    writeln!(output, "    layout::Rect,").unwrap();
    writeln!(output, "    style::{{Color, Modifier, Style}},").unwrap();
    writeln!(output, "    text::Line,").unwrap();
    writeln!(output, "    widgets::{{Block, Borders, Gauge, List, Paragraph, Sparkline, Widget}},").unwrap();
    writeln!(output, "}};\n").unwrap();
    writeln!(output, "#[derive(Clone, Copy)]").unwrap();
    writeln!(output, "pub enum ComponentState {{ Normal, Focused, Active, Disabled }}\n").unwrap();
    writeln!(output, "pub struct {type_name} {{ pub state: ComponentState }}\n").unwrap();
    writeln!(output, "impl Widget for {type_name} {{").unwrap();
    writeln!(output, "    fn render(self, area: Rect, buf: &mut Buffer) {{").unwrap();
    writeln!(output, "        let scale = |rect: Rect| -> Rect {{").unwrap();
    writeln!(
        output,
        "            Rect::new(area.x + rect.x.saturating_mul(area.width) / {}, area.y + rect.y.saturating_mul(area.height) / {}, rect.width.saturating_mul(area.width) / {}, rect.height.saturating_mul(area.height) / {})",
        project.components.width,
        project.components.height,
        project.components.width,
        project.components.height
    )
    .unwrap();
    writeln!(output, "        }};\n").unwrap();

    for widget in &project.components.widgets {
        export_widget(&mut output, widget);
    }

    writeln!(output, "    }}").unwrap();
    writeln!(output, "}}").unwrap();
    output
}

fn export_widget(output: &mut String, widget: &WidgetSpec) {
    let rect = widget.rect;
    let style = rust_style(&widget.styles.normal);
    writeln!(
        output,
        "        let area_{} = scale(Rect::new({}, {}, {}, {}));",
        widget.id, rect.x, rect.y, rect.width, rect.height
    )
    .unwrap();
    match widget.kind {
        WidgetKind::Block => {
            writeln!(
                output,
                "        Block::default().borders(Borders::ALL).title({:?}).style({style}).render(area_{}, buf);",
                widget.title, widget.id
            )
            .unwrap();
        }
        WidgetKind::Paragraph => {
            writeln!(
                output,
                "        Paragraph::new({:?}).block(Block::default().borders(Borders::ALL).title({:?})).style({style}).render(area_{}, buf);",
                widget.text, widget.title, widget.id
            )
            .unwrap();
        }
        WidgetKind::Gauge => {
            writeln!(
                output,
                "        Gauge::default().block(Block::default().borders(Borders::ALL).title({:?})).ratio({:.2}).style({style}).render(area_{}, buf);",
                widget.title,
                f64::from(widget.value.min(100)) / 100.0,
                widget.id
            )
            .unwrap();
        }
        WidgetKind::List => {
            let lines: Vec<&str> = widget.text.lines().collect();
            writeln!(
                output,
                "        List::new({lines:?}).block(Block::default().borders(Borders::ALL).title({:?})).style({style}).render(area_{}, buf);",
                widget.title, widget.id
            )
            .unwrap();
        }
        WidgetKind::Sparkline => {
            let data = parse_sparkline(&widget.text);
            writeln!(output, "        let data_{}: &[u64] = &{data:?};", widget.id).unwrap();
            writeln!(
                output,
                "        Sparkline::default().block(Block::default().borders(Borders::ALL).title({:?})).data(data_{}).style({style}).render(area_{}, buf);",
                widget.title, widget.id, widget.id
            )
            .unwrap();
        }
    }
}

#[must_use]
pub fn export_plain(project: &Project) -> String {
    let mut output = String::new();
    for y in 0..project.canvas().height {
        for x in 0..project.canvas().width {
            let cell = project
                .canvas()
                .composite_cell(crate::model::Point::new(x, y))
                .cloned()
                .unwrap_or_else(Cell::default);
            output.push_str(if cell.transparent { " " } else { &cell.glyph });
        }
        output.push('\n');
    }
    output
}

#[must_use]
pub fn parse_sparkline(text: &str) -> Vec<u64> {
    let parsed: Vec<u64> = text
        .split([',', ' ', '\n'])
        .filter_map(|value| value.trim().parse().ok())
        .collect();
    if parsed.is_empty() {
        vec![2, 4, 3, 7, 5, 9, 8, 12]
    } else {
        parsed
    }
}

fn rust_type_name(name: &str) -> String {
    let mut output = String::new();
    let mut uppercase = true;
    for character in name.chars() {
        if character.is_ascii_alphanumeric() {
            if uppercase {
                output.extend(character.to_uppercase());
                uppercase = false;
            } else {
                output.push(character);
            }
        } else {
            uppercase = true;
        }
    }
    if output.is_empty() {
        "Ratatelier".to_owned()
    } else if output
        .chars()
        .next()
        .is_some_and(|character| character.is_ascii_digit())
    {
        format!("Art{output}")
    } else {
        output
    }
}

fn rust_style(style: &CellStyle) -> String {
    let mut output = format!(
        "Style::default().fg({}).bg({})",
        rust_color(style.fg),
        rust_color(style.bg)
    );
    for (enabled, modifier) in [
        (style.bold, "Modifier::BOLD"),
        (style.dim, "Modifier::DIM"),
        (style.italic, "Modifier::ITALIC"),
        (style.underlined, "Modifier::UNDERLINED"),
        (style.reversed, "Modifier::REVERSED"),
        (style.crossed_out, "Modifier::CROSSED_OUT"),
    ] {
        if enabled {
            write!(output, ".add_modifier({modifier})").unwrap();
        }
    }
    output
}

const fn rust_color(color: ColorSpec) -> &'static str {
    match color {
        ColorSpec::Reset => "Color::Reset",
        ColorSpec::Black => "Color::Black",
        ColorSpec::Red => "Color::Red",
        ColorSpec::Green => "Color::Green",
        ColorSpec::Yellow => "Color::Yellow",
        ColorSpec::Blue => "Color::Blue",
        ColorSpec::Magenta => "Color::Magenta",
        ColorSpec::Cyan => "Color::Cyan",
        ColorSpec::Gray => "Color::Gray",
        ColorSpec::DarkGray => "Color::DarkGray",
        ColorSpec::LightRed => "Color::LightRed",
        ColorSpec::LightGreen => "Color::LightGreen",
        ColorSpec::LightYellow => "Color::LightYellow",
        ColorSpec::LightBlue => "Color::LightBlue",
        ColorSpec::LightMagenta => "Color::LightMagenta",
        ColorSpec::LightCyan => "Color::LightCyan",
        ColorSpec::White => "Color::White",
    }
}

#[allow(dead_code)]
fn _rect(_rect: RectSpec) {}

#[allow(dead_code)]
fn _scene(_scene: &ComponentScene) {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn art_export_contains_painted_glyph() {
        let mut project = Project::new("logo", 3, 2);
        project.canvas_mut().set_cell(
            crate::model::Point::new(1, 0),
            Cell::painted('X', CellStyle::default()),
        );
        let source = export_art(&project);
        assert!(source.contains("\\\"X\\\"") || source.contains("\"X\""));
        assert!(source.contains("impl Widget"));
    }

    #[test]
    fn sparkline_parser_has_fallback() {
        assert!(!parse_sparkline("nonsense").is_empty());
        assert_eq!(parse_sparkline("1, 2, 3"), vec![1, 2, 3]);
    }
}
