use std::fmt::Write;

use crate::model::{
    Canvas, Cell, CellStyle, ColorSpec, ComponentScene, Project, RectSpec, WidgetKind, WidgetSpec,
};

#[must_use]
pub fn export_art(project: &Project) -> String {
    let mut output = String::new();
    let type_name = format!("{}Art", rust_type_name(&project.name));
    write_ratatui_imports(&mut output, false);
    writeln!(output, "pub struct {type_name};\n").unwrap();
    writeln!(output, "impl Widget for {type_name} {{").unwrap();
    writeln!(output, "    fn render(self, area: Rect, buf: &mut Buffer) {{").unwrap();
    write_canvas_render_body(&mut output, project.canvas(), 8);
    writeln!(output, "    }}").unwrap();
    writeln!(output, "}}").unwrap();
    output
}

#[must_use]
pub fn export_animation(project: &Project) -> String {
    let mut output = String::new();
    let type_name = format!("{}Animation", rust_type_name(&project.name));
    writeln!(output, "// Generated by Ratatelier.").unwrap();
    write_ratatui_imports(&mut output, false);
    writeln!(output, "pub const FRAME_DURATIONS_MS: &[u64] = &[").unwrap();
    for frame in &project.frames {
        writeln!(output, "    {},", frame.duration_ms).unwrap();
    }
    writeln!(output, "];\n").unwrap();
    writeln!(
        output,
        "pub const FRAME_COUNT: usize = {};\n",
        project.frames.len()
    )
    .unwrap();
    writeln!(output, "pub struct {type_name} {{ pub frame: usize }}\n").unwrap();
    writeln!(output, "impl Widget for {type_name} {{").unwrap();
    writeln!(output, "    fn render(self, area: Rect, buf: &mut Buffer) {{").unwrap();
    writeln!(output, "        match self.frame % FRAME_COUNT {{").unwrap();
    for index in 0..project.frames.len() {
        writeln!(
            output,
            "            {index} => render_frame_{index}(area, buf),"
        )
        .unwrap();
    }
    writeln!(output, "            _ => unreachable!(),").unwrap();
    writeln!(output, "        }}").unwrap();
    writeln!(output, "    }}").unwrap();
    writeln!(output, "}}\n").unwrap();

    for (index, frame) in project.frames.iter().enumerate() {
        writeln!(
            output,
            "fn render_frame_{index}(area: Rect, buf: &mut Buffer) {{"
        )
        .unwrap();
        write_canvas_render_body(&mut output, &frame.canvas, 4);
        writeln!(output, "}}\n").unwrap();
    }
    output
}

#[must_use]
pub fn export_component(project: &Project) -> String {
    let mut output = String::new();
    let type_name = format!("{}Component", rust_type_name(&project.name));
    write_ratatui_imports(&mut output, true);
    writeln!(output, "#[derive(Clone, Copy)]").unwrap();
    writeln!(
        output,
        "pub enum ComponentState {{ Normal, Focused, Active, Disabled }}\n"
    )
    .unwrap();
    writeln!(
        output,
        "pub struct {type_name} {{ pub state: ComponentState }}\n"
    )
    .unwrap();
    writeln!(output, "impl Widget for {type_name} {{").unwrap();
    writeln!(output, "    fn render(self, area: Rect, buf: &mut Buffer) {{").unwrap();
    writeln!(output, "        let scale = |rect: Rect| -> Rect {{").unwrap();
    writeln!(
        output,
        "            Rect::new(area.x + rect.x.saturating_mul(area.width) / {}, area.y + rect.y.saturating_mul(area.height) / {}, rect.width.saturating_mul(area.width) / {}, rect.height.saturating_mul(area.height) / {})",
        project.components.width,
        project.components.height,
        project.components.width,
        project.components.height
    )
    .unwrap();
    writeln!(output, "        }};\n").unwrap();

    for widget in &project.components.widgets {
        export_widget(&mut output, widget);
    }

    writeln!(output, "    }}").unwrap();
    writeln!(output, "}}").unwrap();
    output
}

#[must_use]
pub fn export_plain(project: &Project) -> String {
    let mut output = String::new();
    for y in 0..project.canvas().height {
        for x in 0..project.canvas().width {
            let cell = project
                .canvas()
                .composite_cell(crate::model::Point::new(x, y))
                .cloned()
                .unwrap_or_else(Cell::default);
            output.push_str(if cell.transparent { " " } else { &cell.glyph });
        }
        output.push('\n');
    }
    output
}

#[must_use]
pub fn export_ansi(project: &Project) -> String {
    let mut output = String::new();
    for y in 0..project.canvas().height {
        let mut active_style: Option<CellStyle> = None;
        for x in 0..project.canvas().width {
            let cell = project
                .canvas()
                .composite_cell(crate::model::Point::new(x, y))
                .cloned()
                .unwrap_or_else(Cell::default);
            if cell.transparent {
                if active_style.take().is_some() {
                    output.push_str("\x1b[0m");
                }
                output.push(' ');
                continue;
            }
            if active_style.as_ref() != Some(&cell.style) {
                output.push_str(&ansi_style(&cell.style));
                active_style = Some(cell.style.clone());
            }
            output.push_str(&cell.glyph);
        }
        if active_style.is_some() {
            output.push_str("\x1b[0m");
        }
        output.push('\n');
    }
    output
}

#[must_use]
pub fn parse_sparkline(text: &str) -> Vec<u64> {
    let parsed: Vec<u64> = text
        .split([',', ' ', '\n'])
        .filter_map(|value| value.trim().parse().ok())
        .collect();
    if parsed.is_empty() {
        vec![2, 4, 3, 7, 5, 9, 8, 12]
    } else {
        parsed
    }
}

fn write_ratatui_imports(output: &mut String, components: bool) {
    writeln!(output, "use ratatui::{{").unwrap();
    writeln!(output, "    buffer::Buffer,").unwrap();
    writeln!(output, "    layout::Rect,").unwrap();
    writeln!(output, "    style::{{Color, Modifier, Style}},").unwrap();
    if components {
        writeln!(output, "    text::Line,").unwrap();
        writeln!(
            output,
            "    widgets::{{Block, Borders, Gauge, List, Paragraph, Sparkline, Widget}},"
        )
        .unwrap();
    } else {
        writeln!(output, "    widgets::Widget,").unwrap();
    }
    writeln!(output, "}};\n").unwrap();
}

fn write_canvas_render_body(output: &mut String, canvas: &Canvas, indent: usize) {
    let padding = " ".repeat(indent);
    writeln!(output, "{padding}const WIDTH: u16 = {};", canvas.width).unwrap();
    writeln!(output, "{padding}const HEIGHT: u16 = {};", canvas.height).unwrap();
    writeln!(
        output,
        "{padding}let origin_x = area.x + area.width.saturating_sub(WIDTH) / 2;"
    )
    .unwrap();
    writeln!(
        output,
        "{padding}let origin_y = area.y + area.height.saturating_sub(HEIGHT) / 2;"
    )
    .unwrap();

    for y in 0..canvas.height {
        for x in 0..canvas.width {
            let point = crate::model::Point::new(x, y);
            let Some(cell) = canvas.composite_cell(point) else {
                continue;
            };
            if cell.transparent {
                continue;
            }
            let style = rust_style(&cell.style);
            writeln!(
                output,
                "{padding}if origin_x + {x} < area.right() && origin_y + {y} < area.bottom() {{"
            )
            .unwrap();
            writeln!(
                output,
                "{padding}    buf[((origin_x + {x}), (origin_y + {y}))].set_symbol({:?}).set_style({style});",
                cell.glyph
            )
            .unwrap();
            writeln!(output, "{padding}}}").unwrap();
        }
    }
}

fn export_widget(output: &mut String, widget: &WidgetSpec) {
    let rect = widget.rect;
    let normal = rust_style(&widget.styles.normal);
    let focused = rust_style(&widget.styles.focused);
    let active = rust_style(&widget.styles.active);
    let disabled = rust_style(&widget.styles.disabled);
    writeln!(
        output,
        "        let area_{} = scale(Rect::new({}, {}, {}, {}));",
        widget.id, rect.x, rect.y, rect.width, rect.height
    )
    .unwrap();
    writeln!(
        output,
        "        let style_{} = match self.state {{",
        widget.id
    )
    .unwrap();
    writeln!(output, "            ComponentState::Normal => {normal},").unwrap();
    writeln!(output, "            ComponentState::Focused => {focused},").unwrap();
    writeln!(output, "            ComponentState::Active => {active},").unwrap();
    writeln!(
        output,
        "            ComponentState::Disabled => {disabled},"
    )
    .unwrap();
    writeln!(output, "        }};").unwrap();
    let style = format!("style_{}", widget.id);
    match widget.kind {
        WidgetKind::Block => {
            writeln!(
                output,
                "        Block::default().borders(Borders::ALL).title({:?}).style({style}).render(area_{}, buf);",
                widget.title, widget.id
            )
            .unwrap();
        }
        WidgetKind::Paragraph => {
            writeln!(
                output,
                "        Paragraph::new({:?}).block(Block::default().borders(Borders::ALL).title({:?})).style({style}).render(area_{}, buf);",
                widget.text, widget.title, widget.id
            )
            .unwrap();
        }
        WidgetKind::Gauge => {
            writeln!(
                output,
                "        Gauge::default().block(Block::default().borders(Borders::ALL).title({:?})).ratio({:.2}).style({style}).render(area_{}, buf);",
                widget.title,
                f64::from(widget.value.min(100)) / 100.0,
                widget.id
            )
            .unwrap();
        }
        WidgetKind::List => {
            let lines: Vec<&str> = widget.text.lines().collect();
            writeln!(
                output,
                "        List::new({lines:?}).block(Block::default().borders(Borders::ALL).title({:?})).style({style}).render(area_{}, buf);",
                widget.title, widget.id
            )
            .unwrap();
        }
        WidgetKind::Sparkline => {
            let data = parse_sparkline(&widget.text);
            writeln!(
                output,
                "        let data_{}: &[u64] = &{data:?};",
                widget.id
            )
            .unwrap();
            writeln!(
                output,
                "        Sparkline::default().block(Block::default().borders(Borders::ALL).title({:?})).data(data_{}).style({style}).render(area_{}, buf);",
                widget.title, widget.id, widget.id
            )
            .unwrap();
        }
    }
}

fn rust_type_name(name: &str) -> String {
    let mut output = String::new();
    let mut uppercase = true;
    for character in name.chars() {
        if character.is_ascii_alphanumeric() {
            if uppercase {
                output.extend(character.to_uppercase());
                uppercase = false;
            } else {
                output.push(character);
            }
        } else {
            uppercase = true;
        }
    }
    if output.is_empty() {
        "Ratatelier".to_owned()
    } else if output
        .chars()
        .next()
        .is_some_and(|character| character.is_ascii_digit())
    {
        format!("Art{output}")
    } else {
        output
    }
}

fn rust_style(style: &CellStyle) -> String {
    let mut output = format!(
        "Style::default().fg({}).bg({})",
        rust_color(style.fg),
        rust_color(style.bg)
    );
    for (enabled, modifier) in [
        (style.bold, "Modifier::BOLD"),
        (style.dim, "Modifier::DIM"),
        (style.italic, "Modifier::ITALIC"),
        (style.underlined, "Modifier::UNDERLINED"),
        (style.reversed, "Modifier::REVERSED"),
        (style.crossed_out, "Modifier::CROSSED_OUT"),
    ] {
        if enabled {
            write!(output, ".add_modifier({modifier})").unwrap();
        }
    }
    output
}

fn ansi_style(style: &CellStyle) -> String {
    let mut codes = vec!["0", ansi_fg(style.fg), ansi_bg(style.bg)];
    for (enabled, code) in [
        (style.bold, "1"),
        (style.dim, "2"),
        (style.italic, "3"),
        (style.underlined, "4"),
        (style.reversed, "7"),
        (style.crossed_out, "9"),
    ] {
        if enabled {
            codes.push(code);
        }
    }
    format!("\x1b[{}m", codes.join(";"))
}

const fn ansi_fg(color: ColorSpec) -> &'static str {
    match color {
        ColorSpec::Reset => "39",
        ColorSpec::Black => "30",
        ColorSpec::Red => "31",
        ColorSpec::Green => "32",
        ColorSpec::Yellow => "33",
        ColorSpec::Blue => "34",
        ColorSpec::Magenta => "35",
        ColorSpec::Cyan => "36",
        ColorSpec::Gray => "37",
        ColorSpec::DarkGray => "90",
        ColorSpec::LightRed => "91",
        ColorSpec::LightGreen => "92",
        ColorSpec::LightYellow => "93",
        ColorSpec::LightBlue => "94",
        ColorSpec::LightMagenta => "95",
        ColorSpec::LightCyan => "96",
        ColorSpec::White => "97",
    }
}

const fn ansi_bg(color: ColorSpec) -> &'static str {
    match color {
        ColorSpec::Reset => "49",
        ColorSpec::Black => "40",
        ColorSpec::Red => "41",
        ColorSpec::Green => "42",
        ColorSpec::Yellow => "43",
        ColorSpec::Blue => "44",
        ColorSpec::Magenta => "45",
        ColorSpec::Cyan => "46",
        ColorSpec::Gray => "47",
        ColorSpec::DarkGray => "100",
        ColorSpec::LightRed => "101",
        ColorSpec::LightGreen => "102",
        ColorSpec::LightYellow => "103",
        ColorSpec::LightBlue => "104",
        ColorSpec::LightMagenta => "105",
        ColorSpec::LightCyan => "106",
        ColorSpec::White => "107",
    }
}

const fn rust_color(color: ColorSpec) -> &'static str {
    match color {
        ColorSpec::Reset => "Color::Reset",
        ColorSpec::Black => "Color::Black",
        ColorSpec::Red => "Color::Red",
        ColorSpec::Green => "Color::Green",
        ColorSpec::Yellow => "Color::Yellow",
        ColorSpec::Blue => "Color::Blue",
        ColorSpec::Magenta => "Color::Magenta",
        ColorSpec::Cyan => "Color::Cyan",
        ColorSpec::Gray => "Color::Gray",
        ColorSpec::DarkGray => "Color::DarkGray",
        ColorSpec::LightRed => "Color::LightRed",
        ColorSpec::LightGreen => "Color::LightGreen",
        ColorSpec::LightYellow => "Color::LightYellow",
        ColorSpec::LightBlue => "Color::LightBlue",
        ColorSpec::LightMagenta => "Color::LightMagenta",
        ColorSpec::LightCyan => "Color::LightCyan",
        ColorSpec::White => "Color::White",
    }
}

#[allow(dead_code)]
fn _rect(_rect: RectSpec) {}

#[allow(dead_code)]
fn _scene(_scene: &ComponentScene) {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn art_export_contains_painted_glyph() {
        let mut project = Project::new("logo", 3, 2);
        project.canvas_mut().set_cell(
            crate::model::Point::new(1, 0),
            Cell::painted('X', CellStyle::default()),
        );
        let source = export_art(&project);
        assert!(source.contains("\\\"X\\\"") || source.contains("\"X\""));
        assert!(source.contains("impl Widget"));
    }

    #[test]
    fn animation_export_preserves_style_and_duration() {
        let mut project = Project::new("blink", 2, 1);
        project.frame_mut().duration_ms = 350;
        project.canvas_mut().set_cell(
            crate::model::Point::new(0, 0),
            Cell::painted(
                'X',
                CellStyle {
                    fg: ColorSpec::LightCyan,
                    bold: true,
                    ..CellStyle::default()
                },
            ),
        );
        let source = export_animation(&project);
        assert!(source.contains("350"));
        assert!(source.contains("Color::LightCyan"));
        assert!(source.contains("Modifier::BOLD"));
    }

    #[test]
    fn ansi_export_contains_style_and_reset_sequences() {
        let mut project = Project::new("ansi", 1, 1);
        project.canvas_mut().set_cell(
            crate::model::Point::new(0, 0),
            Cell::painted(
                'X',
                CellStyle {
                    fg: ColorSpec::LightGreen,
                    underlined: true,
                    ..CellStyle::default()
                },
            ),
        );
        let output = export_ansi(&project);
        assert!(output.contains("\x1b[0;92;49;4mX\x1b[0m"));
    }

    #[test]
    fn component_export_uses_all_widget_states() {
        let project = Project::new("component", 2, 1);
        let source = export_component(&project);
        assert!(source.contains("ComponentState::Focused"));
        assert!(source.contains("ComponentState::Disabled"));
    }

    #[test]
    fn sparkline_parser_has_fallback() {
        assert!(!parse_sparkline("nonsense").is_empty());
        assert_eq!(parse_sparkline("1, 2, 3"), vec![1, 2, 3]);
    }
}
