use std::fmt::Write;

use crate::model::{Canvas, Cell, CellStyle, ColorSpec, Project, WidgetKind, WidgetSpec};

#[must_use]
pub fn export_art(project: &Project) -> String {
    let mut output = String::new();
    let type_name = format!("{}Art", rust_type_name(&project.name));
    write_ratatui_imports(&mut output, false);
    writeln!(output, "pub struct {type_name};\n").unwrap();
    writeln!(output, "impl Widget for {type_name} {{").unwrap();
    writeln!(
        output,
        "    fn render(self, area: Rect, buf: &mut Buffer) {{"
    )
    .unwrap();
    write_canvas_render_body(&mut output, project.canvas(), 8);
    writeln!(output, "    }}").unwrap();
    writeln!(output, "}}").unwrap();
    output
}

#[must_use]
pub fn export_animation(project: &Project) -> String {
    let mut output = String::new();
    let type_name = format!("{}Animation", rust_type_name(&project.name));
    writeln!(output, "// Generated by Ratatelier.").unwrap();
    write_ratatui_imports(&mut output, false);
    writeln!(output, "pub const FRAME_DURATIONS_MS: &[u64] = &[").unwrap();
    for (index, frame) in project.frames.iter().enumerate() {
        writeln!(output, "    {}, // frame {}", frame.duration_ms, index + 1).unwrap();
    }
    writeln!(output, "];\n").unwrap();
    writeln!(
        output,
        "pub const FRAME_COUNT: usize = {};\n",
        project.frames.len()
    )
    .unwrap();
    writeln!(output, "pub struct {type_name} {{").unwrap();
    writeln!(output, "    pub frame: usize,").unwrap();
    writeln!(output, "}}\n").unwrap();
    writeln!(output, "impl Widget for {type_name} {{").unwrap();
    writeln!(
        output,
        "    fn render(self, area: Rect, buf: &mut Buffer) {{"
    )
    .unwrap();
    writeln!(output, "        match self.frame % FRAME_COUNT {{").unwrap();
    for index in 0..project.frames.len() {
        writeln!(
            output,
            "            {index} => render_frame_{index}(area, buf),"
        )
        .unwrap();
    }
    writeln!(output, "            _ => unreachable!(),").unwrap();
    writeln!(output, "        }}").unwrap();
    writeln!(output, "    }}").unwrap();
    writeln!(output, "}}\n").unwrap();

    for (index, frame) in project.frames.iter().enumerate() {
        writeln!(
            output,
            "fn render_frame_{index}(area: Rect, buf: &mut Buffer) {{"
        )
        .unwrap();
        write_canvas_render_body(&mut output, &frame.canvas, 4);
        writeln!(output, "}}").unwrap();
        if index + 1 < project.frames.len() {
            writeln!(output).unwrap();
        }
    }
    output
}

#[must_use]
pub fn export_component(project: &Project) -> String {
    let mut output = String::new();
    let type_name = format!("{}Component", rust_type_name(&project.name));
    write_ratatui_imports(&mut output, true);
    writeln!(output, "#[derive(Clone, Copy)]").unwrap();
    writeln!(output, "pub enum ComponentState {{").unwrap();
    writeln!(output, "    Normal,").unwrap();
    writeln!(output, "    Focused,").unwrap();
    writeln!(output, "    Active,").unwrap();
    writeln!(output, "    Disabled,").unwrap();
    writeln!(output, "}}\n").unwrap();
    writeln!(output, "pub struct {type_name} {{").unwrap();
    writeln!(output, "    pub state: ComponentState,").unwrap();
    writeln!(output, "}}\n").unwrap();
    writeln!(output, "impl Widget for {type_name} {{").unwrap();
    writeln!(
        output,
        "    fn render(self, area: Rect, buf: &mut Buffer) {{"
    )
    .unwrap();
    writeln!(output, "        let scale = |rect: Rect| -> Rect {{").unwrap();
    writeln!(
        output,
        "            let x = area.x + rect.x.saturating_mul(area.width) / {};",
        project.components.width
    )
    .unwrap();
    writeln!(
        output,
        "            let y = area.y + rect.y.saturating_mul(area.height) / {};",
        project.components.height
    )
    .unwrap();
    writeln!(
        output,
        "            let width = rect.width.saturating_mul(area.width) / {};",
        project.components.width
    )
    .unwrap();
    writeln!(
        output,
        "            let height = rect.height.saturating_mul(area.height) / {};",
        project.components.height
    )
    .unwrap();
    writeln!(output, "            Rect::new(x, y, width, height)").unwrap();
    writeln!(output, "        }};\n").unwrap();

    for widget in &project.components.widgets {
        export_widget(&mut output, widget);
    }

    writeln!(output, "    }}").unwrap();
    writeln!(output, "}}").unwrap();
    output
}

#[must_use]
pub fn export_plain(project: &Project) -> String {
    let mut output = String::new();
    for y in 0..project.canvas().height {
        for x in 0..project.canvas().width {
            let cell = project
                .canvas()
                .composite_cell(crate::model::Point::new(x, y))
                .cloned()
                .unwrap_or_else(Cell::default);
            output.push_str(if cell.transparent { " " } else { &cell.glyph });
        }
        output.push('\n');
    }
    output
}

#[must_use]
pub fn export_ansi(project: &Project) -> String {
    let mut output = String::new();
    for y in 0..project.canvas().height {
        let mut active_style: Option<CellStyle> = None;
        for x in 0..project.canvas().width {
            let cell = project
                .canvas()
                .composite_cell(crate::model::Point::new(x, y))
                .cloned()
                .unwrap_or_else(Cell::default);
            if cell.transparent {
                if active_style.take().is_some() {
                    output.push_str("\x1b[0m");
                }
                output.push(' ');
                continue;
            }
            if active_style.as_ref() != Some(&cell.style) {
                output.push_str(&ansi_style(&cell.style));
                active_style = Some(cell.style.clone());
            }
            output.push_str(&cell.glyph);
        }
        if active_style.is_some() {
            output.push_str("\x1b[0m");
        }
        output.push('\n');
    }
    output
}

#[must_use]
pub fn parse_sparkline(text: &str) -> Vec<u64> {
    let parsed: Vec<u64> = text
        .split([',', ' ', '\n'])
        .filter_map(|value| value.trim().parse().ok())
        .collect();
    if parsed.is_empty() {
        vec![2, 4, 3, 7, 5, 9, 8, 12]
    } else {
        parsed
    }
}

fn write_ratatui_imports(output: &mut String, components: bool) {
    writeln!(output, "use ratatui::{{").unwrap();
    writeln!(output, "    buffer::Buffer,").unwrap();
    writeln!(output, "    layout::Rect,").unwrap();
    writeln!(output, "    style::{{Color, Modifier, Style}},").unwrap();
    if components {
        writeln!(
            output,
            "    widgets::{{Block, Borders, Gauge, List, Paragraph, Sparkline, Widget}},"
        )
        .unwrap();
    } else {
        writeln!(output, "    widgets::Widget,").unwrap();
    }
    writeln!(output, "}};\n").unwrap();
}

fn write_canvas_render_body(output: &mut String, canvas: &Canvas, indent: usize) {
    let padding = " ".repeat(indent);
    writeln!(output, "{padding}const WIDTH: u16 = {};", canvas.width).unwrap();
    writeln!(output, "{padding}const HEIGHT: u16 = {};", canvas.height).unwrap();
    writeln!(
        output,
        "{padding}let origin_x = area.x + area.width.saturating_sub(WIDTH) / 2;"
    )
    .unwrap();
    writeln!(
        output,
        "{padding}let origin_y = area.y + area.height.saturating_sub(HEIGHT) / 2;"
    )
    .unwrap();

    for y in 0..canvas.height {
        for x in 0..canvas.width {
            let point = crate::model::Point::new(x, y);
            let Some(cell) = canvas.composite_cell(point) else {
                continue;
            };
            if cell.transparent {
                continue;
            }
            writeln!(
                output,
                "{padding}if origin_x + {x} < area.right() && origin_y + {y} < area.bottom() {{"
            )
            .unwrap();
            write_style_bindings(output, &(padding.clone() + "    "), "style", &cell.style);
            writeln!(
                output,
                "{padding}    let cell = &mut buf[(origin_x + {x}, origin_y + {y})];"
            )
            .unwrap();
            writeln!(output, "{padding}    cell.set_symbol({:?});", cell.glyph).unwrap();
            writeln!(output, "{padding}    cell.set_style(style);").unwrap();
            writeln!(output, "{padding}}}").unwrap();
        }
    }
}

fn write_style_bindings(output: &mut String, padding: &str, variable: &str, style: &CellStyle) {
    writeln!(output, "{padding}let {variable} = Style::default();").unwrap();
    writeln!(
        output,
        "{padding}let {variable} = {variable}.fg({});",
        rust_color(style.fg)
    )
    .unwrap();
    writeln!(
        output,
        "{padding}let {variable} = {variable}.bg({});",
        rust_color(style.bg)
    )
    .unwrap();
    for (enabled, modifier) in [
        (style.bold, "Modifier::BOLD"),
        (style.dim, "Modifier::DIM"),
        (style.italic, "Modifier::ITALIC"),
        (style.underlined, "Modifier::UNDERLINED"),
        (style.reversed, "Modifier::REVERSED"),
        (style.crossed_out, "Modifier::CROSSED_OUT"),
    ] {
        if enabled {
            writeln!(
                output,
                "{padding}let {variable} = {variable}.add_modifier({modifier});"
            )
            .unwrap();
        }
    }
}

fn write_style_match_arm(output: &mut String, state: &str, style: &CellStyle) {
    writeln!(output, "            ComponentState::{state} => {{").unwrap();
    write_style_bindings(output, "                ", "style", style);
    writeln!(output, "                style").unwrap();
    writeln!(output, "            }},").unwrap();
}

fn export_widget(output: &mut String, widget: &WidgetSpec) {
    let rect = widget.rect;
    writeln!(
        output,
        "        let area_{} = scale(Rect::new({}, {}, {}, {}));",
        widget.id, rect.x, rect.y, rect.width, rect.height
    )
    .unwrap();
    writeln!(
        output,
        "        let style_{} = match self.state {{",
        widget.id
    )
    .unwrap();
    write_style_match_arm(output, "Normal", &widget.styles.normal);
    write_style_match_arm(output, "Focused", &widget.styles.focused);
    write_style_match_arm(output, "Active", &widget.styles.active);
    write_style_match_arm(output, "Disabled", &widget.styles.disabled);
    writeln!(output, "        }};").unwrap();
    writeln!(
        output,
        "        let title_{} = {:?};",
        widget.id, widget.title
    )
    .unwrap();
    writeln!(
        output,
        "        let block_{} = Block::default();",
        widget.id
    )
    .unwrap();
    writeln!(
        output,
        "        let block_{} = block_{}.borders(Borders::ALL);",
        widget.id, widget.id
    )
    .unwrap();
    writeln!(
        output,
        "        let block_{} = block_{}.title(title_{});",
        widget.id, widget.id, widget.id
    )
    .unwrap();

    match widget.kind {
        WidgetKind::Block => {
            writeln!(
                output,
                "        let widget_{} = block_{}.style(style_{});",
                widget.id, widget.id, widget.id
            )
            .unwrap();
        }
        WidgetKind::Paragraph => {
            writeln!(
                output,
                "        let text_{} = {:?};",
                widget.id, widget.text
            )
            .unwrap();
            writeln!(
                output,
                "        let widget_{} = Paragraph::new(text_{});",
                widget.id, widget.id
            )
            .unwrap();
            writeln!(
                output,
                "        let widget_{} = widget_{}.block(block_{});",
                widget.id, widget.id, widget.id
            )
            .unwrap();
            writeln!(
                output,
                "        let widget_{} = widget_{}.style(style_{});",
                widget.id, widget.id, widget.id
            )
            .unwrap();
        }
        WidgetKind::Gauge => {
            writeln!(
                output,
                "        let widget_{} = Gauge::default();",
                widget.id
            )
            .unwrap();
            writeln!(
                output,
                "        let widget_{} = widget_{}.block(block_{});",
                widget.id, widget.id, widget.id
            )
            .unwrap();
            writeln!(
                output,
                "        let widget_{} = widget_{}.ratio({:.2});",
                widget.id,
                widget.id,
                f64::from(widget.value.min(100)) / 100.0
            )
            .unwrap();
            writeln!(
                output,
                "        let widget_{} = widget_{}.style(style_{});",
                widget.id, widget.id, widget.id
            )
            .unwrap();
        }
        WidgetKind::List => {
            writeln!(output, "        let mut items_{} = Vec::new();", widget.id).unwrap();
            for line in widget.text.lines() {
                writeln!(output, "        items_{}.push({line:?});", widget.id).unwrap();
            }
            writeln!(
                output,
                "        let widget_{} = List::new(items_{});",
                widget.id, widget.id
            )
            .unwrap();
            writeln!(
                output,
                "        let widget_{} = widget_{}.block(block_{});",
                widget.id, widget.id, widget.id
            )
            .unwrap();
            writeln!(
                output,
                "        let widget_{} = widget_{}.style(style_{});",
                widget.id, widget.id, widget.id
            )
            .unwrap();
        }
        WidgetKind::Sparkline => {
            let data = parse_sparkline(&widget.text);
            writeln!(output, "        let data_{}: &[u64] = &[", widget.id).unwrap();
            for (index, value) in data.iter().enumerate() {
                writeln!(output, "            {value}, // point {}", index + 1).unwrap();
            }
            writeln!(output, "        ];").unwrap();
            writeln!(
                output,
                "        let widget_{} = Sparkline::default();",
                widget.id
            )
            .unwrap();
            writeln!(
                output,
                "        let widget_{} = widget_{}.block(block_{});",
                widget.id, widget.id, widget.id
            )
            .unwrap();
            writeln!(
                output,
                "        let widget_{} = widget_{}.data(data_{});",
                widget.id, widget.id, widget.id
            )
            .unwrap();
            writeln!(
                output,
                "        let widget_{} = widget_{}.style(style_{});",
                widget.id, widget.id, widget.id
            )
            .unwrap();
        }
    }
    writeln!(
        output,
        "        widget_{}.render(area_{}, buf);",
        widget.id, widget.id
    )
    .unwrap();
}

fn rust_type_name(name: &str) -> String {
    let mut output = String::new();
    let mut uppercase = true;
    for character in name.chars() {
        if character.is_ascii_alphanumeric() {
            if uppercase {
                output.extend(character.to_uppercase());
                uppercase = false;
            } else {
                output.push(character);
            }
        } else {
            uppercase = true;
        }
    }
    if output.is_empty() {
        "Ratatelier".to_owned()
    } else if output
        .chars()
        .next()
        .is_some_and(|character| character.is_ascii_digit())
    {
        format!("Art{output}")
    } else {
        output
    }
}

fn ansi_style(style: &CellStyle) -> String {
    let mut codes = vec!["0", ansi_fg(style.fg), ansi_bg(style.bg)];
    for (enabled, code) in [
        (style.bold, "1"),
        (style.dim, "2"),
        (style.italic, "3"),
        (style.underlined, "4"),
        (style.reversed, "7"),
        (style.crossed_out, "9"),
    ] {
        if enabled {
            codes.push(code);
        }
    }
    format!("\x1b[{}m", codes.join(";"))
}

const fn ansi_fg(color: ColorSpec) -> &'static str {
    match color {
        ColorSpec::Reset => "39",
        ColorSpec::Black => "30",
        ColorSpec::Red => "31",
        ColorSpec::Green => "32",
        ColorSpec::Yellow => "33",
        ColorSpec::Blue => "34",
        ColorSpec::Magenta => "35",
        ColorSpec::Cyan => "36",
        ColorSpec::Gray => "37",
        ColorSpec::DarkGray => "90",
        ColorSpec::LightRed => "91",
        ColorSpec::LightGreen => "92",
        ColorSpec::LightYellow => "93",
        ColorSpec::LightBlue => "94",
        ColorSpec::LightMagenta => "95",
        ColorSpec::LightCyan => "96",
        ColorSpec::White => "97",
    }
}

const fn ansi_bg(color: ColorSpec) -> &'static str {
    match color {
        ColorSpec::Reset => "49",
        ColorSpec::Black => "40",
        ColorSpec::Red => "41",
        ColorSpec::Green => "42",
        ColorSpec::Yellow => "43",
        ColorSpec::Blue => "44",
        ColorSpec::Magenta => "45",
        ColorSpec::Cyan => "46",
        ColorSpec::Gray => "47",
        ColorSpec::DarkGray => "100",
        ColorSpec::LightRed => "101",
        ColorSpec::LightGreen => "102",
        ColorSpec::LightYellow => "103",
        ColorSpec::LightBlue => "104",
        ColorSpec::LightMagenta => "105",
        ColorSpec::LightCyan => "106",
        ColorSpec::White => "107",
    }
}

const fn rust_color(color: ColorSpec) -> &'static str {
    match color {
        ColorSpec::Reset => "Color::Reset",
        ColorSpec::Black => "Color::Black",
        ColorSpec::Red => "Color::Red",
        ColorSpec::Green => "Color::Green",
        ColorSpec::Yellow => "Color::Yellow",
        ColorSpec::Blue => "Color::Blue",
        ColorSpec::Magenta => "Color::Magenta",
        ColorSpec::Cyan => "Color::Cyan",
        ColorSpec::Gray => "Color::Gray",
        ColorSpec::DarkGray => "Color::DarkGray",
        ColorSpec::LightRed => "Color::LightRed",
        ColorSpec::LightGreen => "Color::LightGreen",
        ColorSpec::LightYellow => "Color::LightYellow",
        ColorSpec::LightBlue => "Color::LightBlue",
        ColorSpec::LightMagenta => "Color::LightMagenta",
        ColorSpec::LightCyan => "Color::LightCyan",
        ColorSpec::White => "Color::White",
    }
}

#[cfg(test)]
mod tests {
    use std::{
        fs,
        process::Command,
        sync::atomic::{AtomicUsize, Ordering},
    };

    use super::*;

    static RUSTFMT_FIXTURE: AtomicUsize = AtomicUsize::new(0);

    fn assert_rustfmt_clean(label: &str, source: &str) {
        let nonce = RUSTFMT_FIXTURE.fetch_add(1, Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!(
            "ratatelier-{label}-{}-{nonce}.rs",
            std::process::id()
        ));
        fs::write(&path, source).expect("generated source fixture should write");

        let mut version_command = Command::new("rustfmt");
        version_command.arg("--version");
        let availability = match version_command.output() {
            Ok(output) => output,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                let _ = fs::remove_file(&path);
                return;
            }
            Err(error) => {
                let _ = fs::remove_file(&path);
                panic!("failed to check rustfmt for {label}: {error}");
            }
        };
        if !availability.status.success() {
            let stderr = String::from_utf8_lossy(&availability.stderr);
            if stderr.contains("not installed for the toolchain") {
                let _ = fs::remove_file(&path);
                return;
            }
            let _ = fs::remove_file(&path);
            panic!("rustfmt availability check failed for {label}: {stderr}");
        }

        let mut check_command = Command::new("rustfmt");
        check_command.arg("--check");
        check_command.arg(&path);
        let status = check_command
            .status()
            .expect("rustfmt availability was already verified");
        let _ = fs::remove_file(&path);
        assert!(status.success(), "{label} export was not rustfmt-clean");
    }

    #[test]
    fn art_export_contains_painted_glyph() {
        let mut project = Project::new("logo", 3, 2);
        project.canvas_mut().set_cell(
            crate::model::Point::new(1, 0),
            Cell::painted('X', CellStyle::default()),
        );
        let source = export_art(&project);
        assert!(source.contains("\\\"X\\\"") || source.contains("\"X\""));
        assert!(source.contains("impl Widget"));
        assert_rustfmt_clean("art", &source);
    }

    #[test]
    fn animation_export_preserves_style_and_duration() {
        let mut project = Project::new("blink", 2, 1);
        project.frame_mut().duration_ms = 350;
        project.canvas_mut().set_cell(
            crate::model::Point::new(0, 0),
            Cell::painted(
                'X',
                CellStyle {
                    fg: ColorSpec::LightCyan,
                    bold: true,
                    ..CellStyle::default()
                },
            ),
        );
        let source = export_animation(&project);
        assert!(source.contains("350"));
        assert!(source.contains("Color::LightCyan"));
        assert!(source.contains("Modifier::BOLD"));
        assert_rustfmt_clean("animation", &source);
    }

    #[test]
    fn ansi_export_contains_style_and_reset_sequences() {
        let mut project = Project::new("ansi", 1, 1);
        project.canvas_mut().set_cell(
            crate::model::Point::new(0, 0),
            Cell::painted(
                'X',
                CellStyle {
                    fg: ColorSpec::LightGreen,
                    underlined: true,
                    ..CellStyle::default()
                },
            ),
        );
        let output = export_ansi(&project);
        assert!(output.contains("\x1b[0;92;49;4mX\x1b[0m"));
    }

    #[test]
    fn component_export_uses_all_widget_states() {
        let project = Project::new("component", 2, 1);
        let source = export_component(&project);
        assert!(source.contains("ComponentState::Focused"));
        assert!(source.contains("ComponentState::Disabled"));
        assert_rustfmt_clean("component", &source);
    }

    #[test]
    fn sparkline_parser_has_fallback() {
        assert!(!parse_sparkline("nonsense").is_empty());
        assert_eq!(parse_sparkline("1, 2, 3"), vec![1, 2, 3]);
    }
}
